version: '2'
services:
  mysqltesting: 
    build: .
    image: mysqltesting 
    ports:
      - "3306:3306"
      - "8080:8080"
    user: "100000"
    environment:
      - SUPERVISORD_LOGLEVEL=debug
      - MYSQL_USER=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_PASSWORD=Fhtest123!
